---
version: "3.7"

services:
  server:
      image: gitea/gitea:1.21.4
      container_name: gitea
      environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=
      - GITEA__database__USER=
      - GITEA__database__PASSWD=
      restart: always
      volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:chicago/us
      - /etc/localtime:/etc/localtime:chicago/us
      depends_on:
      - db
      networks:

    security_opt:
      - no-new-privileges:true

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    volumes:
      - ./postgres:/var/lib/postgresql/data
