---
services:

  vaultwarden:
    image: vaultwarden/server:1.32.6-alpine
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - ./data/:/data/
    networks:
      - proxy
    environment:
      - TZ=UTC
      - DATABASE_URL="${DATABASE_URL}"
      # Mail Server
      - SMTP_HOST="${SMTP_HOST}"
      - SMTP_FROM="${SMTP_FROM}"
      - SMTP_FROM_NAME="${SMTP_FROM_NAME}"
      - SMTP_PORT="${SMTP_PORT}"
      - SMTP_SECURITY="${SMTP_SECURITY}"
      - SMTP_USERNAME="${SMTP_USERNAME}"
      - SMTP_PASSWORD="${SMTP_PASSWORD}"
      - SMTP_EMBED_IMAGES="${SMTP_EMBED_IMAGES}"
      - SMTP_TIMEOUT=30
      - SMTP_AUTH_MECHANISM="${SMTP_AUTH_MECHANISM}"
      # App Configs
      - LOGIN_RATELIMIT_MAX_BURST=10
      - LOGIN_RATELIMIT_SECONDS=60
      - DOMAIN=https://vault.example.com
      - INVITATIONS_ALLOWED=true
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - WEB_VAULT_ENABLED=true
      - WEBSOCKET_ENABLED=true
      - PASSWORD_ITERATIONS=500000
      - SHOW_PASSWORD_HINT="${SHOW_PASSWORD_HINT}"
      - EMAIL_CHANGE_ALLOWED="${EMAIL_CHANGE_ALLOWED}"
      # Organisation Events
      - ORG_EVENTS_ENABLED="${ORG_EVENTS_ENABLED}"
      - ORG_GROUPS_ENABLED="${ORG_GROUPS_ENABLED}"
      - INVITATION_ORG_NAME="${INVITATION_ORG_NAME}"
      - EVENT_CLEANUP_SCHEDULE="0 0 * * *"
      - SIGNUPS_ALLOWED="${SIGNUPS_ALLOWED}"
      - SIGNUPS_DOMAINS_WHITELIST="${SIGNUPS_DOMAINS_WHITELIST}"
      - SIGNUPS_VERIFY=true
      - SIGNUPS_VERIFY_RESEND_TIME=3600
      - SIGNUPS_VERIFY_RESEND_LIMIT=6
      - EMERGENCY_ACCESS_ALLOWED="${EMERGENCY_ACCESS_ALLOWED}"
      - SENDS_ALLOWED="${SENDS_ALLOWED}"
      # Push Notifications
      - PUSH_ENABLED="${PUSH_ENABLED}"
      - PUSH_INSTALLATION_ID="${PUSH_INSTALLATION_ID}"
      - PUSH_INSTALLATION_KEY="${PUSH_INSTALLATION_KEY}"
      - PUSH_RELAY_URI="${PUSH_RELAY_URI}"
      - PUSH_IDENTITY_URI="${PUSH_IDENTITY_URI}"
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.tls=true"
      - "traefik.http.routers.vaultwarden.entrypoints=https"
      - "traefik.http.routers.vaultwarden.rule=Host(`vault.example.com`)"
      - "traefik.http.routers.vaultwarden.service=vaultwarden"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

volumes:
  data:
    driver: local

networks:
  proxy:
    external: true