---
services:

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:main-ubuntu
    restart: unless-stopped
    user: "0"
    networks:
      - grafana-net
      - proxy
    volumes:
      - ./grafana-data/grafana:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=http"
      - "traefik.http.routers.grafana.rule=Host(`grafana.example.com`)"
      - "traefik.http.routers.grafana.middlewares=default-whitelist@file"
      - "traefik.http.middlewares.grafana-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.grafana.middlewares=grafana-https-redirect"
      - "traefik.http.routers.grafana.entrypoints=https"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"

  influxdb:
    container_name: influxdb
    image: influxdb:latest
    restart: unless-stopped
    ports:
      - 8086:8086
      - 8089:8089/udp
    networks:
      - grafana-net
    volumes:
      - ./grafana-data/influxdb:/var/lib/influxdb2

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      - grafana-net
    volumes:
      - ./grafana-data/prometheus/data:/prometheus/data
      - ./grafana-data/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - snmp-exporter

  snmp-exporter:
    image: prom/snmp-exporter:latest
    container_name: snmp-exporter
    restart: unless-stopped
    ports:
      - "9116:9116"
    networks:
      - grafana-net
      - proxy
    volumes:
      - ./snmp-exporter-config/snmp.yml:/etc/snmp_exporter/snmp.yml

volumes:
  grafana-data:
    driver: local
  snmp-exporter-config:
    driver: local

networks:
  grafana-net:
  proxy:
    external: true
