---
- name: Ensure all necessary groups are created
  group:
    name: "{{ item }}"
  loop:
    - docker
    - samba

- name: Ensure the non-root user is created
  user:
    name: "{{ username }}"
    group:
      - sudo
      - docker
      - users
    append: yes
    shell: "{{ shell }}"

- name: Enable passwordless sudo for User
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"