---
- hosts: all
  become: true
  tasks:
    - name: Disable SSH password auth
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^#PasswordAuthentication yes"
        line: "PasswordAuthentication no"
      notify: Restart SSH daemon

    - name: Update SSH configuration to be more secure
      ansible.builtin.lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
        validate: "sshd -T -f %s"
        mode: 0644
      loop:
        - regexp: "^#?PasswordAuthentication"
          line: "PasswordAuthentication no"
        - regexp: "^#?PermitRootLogin"
          line: "PermitRootLogin no"
        - regexp: "^#?PermitEmptyPasswords"
          line: "PermitEmptyPasswords no"
        - regexp: "^#?X11Forwarding"
          line: "X11Forwarding no"
      notify: Restart SSH daemon
  handlers:
    - name: Restart SSH daemon
      ansible.builtin.service:
        name: sshd
        state: restarted
