version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8085:8085 # qbittorrent
      - 9117:9117 # Jackett
      - 8989:8989 # Sonarr
      - 7878:7878 # Radarr
    volumes:
      - /home/$USER/docker/arr-stack:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=<YOUR_PRIVATE_KEY> # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/mullvad.md and https://github.com/qdm12/gluetun/discussions/805#discussioncomment-2026642
      - WIREGUARD_ADDRESSES=<Wireguard Config File>
      - City=NewYork NY
      - TZ=US/Chicago
      - UPDATER_PERIOD=24h

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Chicago
      - WEBUI_PORT=8085
    volumes:
      - /home/$USER/docker/arr-stack/qbittorrent:/config
      - /home/$USER/docker/arr-stack/qbittorrent/downloads:/downloads
    depends_on:
      - gluetun
    restart: always

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Chicago
      - AUTO_UPDATE=true
    volumes:
      - /home/$USER/docker/arr-stack/jackett/data:/config
      - /home/$USER/docker/arr-stack/jackett/blackhole:/downloads
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Chicago
    volumes:
      - /home/$USER/docker/arr-stack/sonarr/data:/config
      - /home/$USER/docker/arr-stack/sonarr/tvseries:/tv
      - /home/$USER/docker/arr-stack/sonarr/downloadclient-downloads:/downloads
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Chicago
    volumes:
      - /home/$USER/docker/arr-stack/radarr/data:/config
      - /home/$USER/docker/arr-stack/radarr/movies:/movies
      - /home/$USER/docker/arr-stack/radarr/downloadclient-downloads:/downloads
    restart: unless-stopped
