---
services:

  glance:
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - ./glance.yml:/app/glance.yml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glance.tls=true"
      - "traefik.http.routers.glance.entrypoints=http"
      - "traefik.http.routers.glance.rule=Host(`glance.example.com`)"
      - "traefik.http.routers.glance.entrypoints=https"
      - "traefik.http.routers.glance-secure.service=glance"
      - "traefik.http.routers.glance.tls.certresolver=cloudflare"
      - "traefik.http.services.glance.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
